FROM alpine:latest

RUN apk update && \
    apk add --no-cache \
    gcc g++ \
    musl-dev \
    cmake \
    make \
    zeromq-dev \
    pkgconf \
    bash \
    git \
    vim

WORKDIR /app

CMD ["/bin/bash"]